name: iOS Build

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-14 # Revert to macOS 14 which retains pre-installed iOS simulators

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Cache Homebrew
        uses: actions/cache@v4
        id: cache-homebrew
        with:
          path: |
            /usr/local/Cellar
            /usr/local/Homebrew
            /opt/homebrew
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/ios.yml') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-
            
      - name: Install Dependencies
        if: steps.cache-homebrew.outputs.cache-hit != 'true'
        run: brew install xcodegen swiftlint

      - name: Generate Project
        run: |
          cd GD-MangaReader
          echo "GID_CLIENT_ID = dummy_client_id" > Secrets.xcconfig
          echo "GID_REVERSED_CLIENT_ID = com.googleusercontent.apps.dummy_client_id" >> Secrets.xcconfig
          xcodegen generate
          
      - name: SwiftLint
        run: swiftlint --strict || echo "SwiftLint found issues, but continuing build"
      - name: Build
        run: |
          cd GD-MangaReader
          xcodebuild build -scheme GD-MangaReader -project GD-MangaReader.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' | xcpretty && exit ${PIPESTATUS[0]}
