name: iOS Build

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-15 # Upgrade to macOS 15 for Xcode 16+ (Format 77)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Project
        run: |
          cd GD-MangaReader
          echo "GID_CLIENT_ID = dummy_client_id" > Secrets.xcconfig
          echo "GID_REVERSED_CLIENT_ID = com.googleusercontent.apps.dummy_client_id" >> Secrets.xcconfig
          xcodegen generate
      - name: Build
        run: |
          cd GD-MangaReader
          xcodebuild build -scheme GD-MangaReader -project GD-MangaReader.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' | xcpretty && exit ${PIPESTATUS[0]}
